name: 'Create Sales Ops issue'
author: 'NickLiffen'
description: 'An Issue that creates a Sales Ops Issue'
inputs:
  issueBodyPayload:
    description: 'The Issue Body Payload in a JSON Format'
    required: true
  approver:
    description: 'Who Approved the Trial? GitHub Username'
    required: true
  issueNumber:
    description: 'Who Approved the Trial? GitHub Username'
    required: true
  githubToken:
    description: 'The Token to create an issue on the Sales Ops Issue'
    required: true
  githubRepository:
    description: 'The GitHub Repository to create the Issue on'
    required: true
outputs:
  opsIssueNumber:
    description: 'The Issue Number Created in the Ops Repo'
  opsIssueURL:
    description: 'The Issue url Created in the Ops Repo'
  opsGHECIssueNumber:
    description: 'The Issue Number Created in the Ops Repo for a GHEC Trial'
  opsGHECIssueURL:
    description: 'The Issue url Created in the Ops Repo for a GHEC Trial'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'target'  
  color: 'blue'